- playground/src/pages/CameraControlsDemo.vue
````
$ pnpm run lint
> ./cientos/playground/src/pages/CameraControlsDemo.vue
> 89:1  warning  This line has a length of 125. Maximum allowed is 120  max-len 
````
Broke line 89.
The contribution docs say you accept PRs for spelling mistakes and that PRs should be linted before submitting, so I don't think this is out of place, but feel free to close if it is.
> chore: fix linter warning

- src/core/controls/CameraControls.vue
- src/core/controls/MapControls.vue
- src/core/controls/OrbitControls.vue
- src/core/controls/PointerLockControls.vue
It appears that the `domElement` and the `camera` props cannot be overwritten in `Controls` components. This PR fixes it.
> fix(cientos): controls' props priority

- docs/guide/misc/stats.md
- playground/src/pages/controls/FirstPersonControlsDemo.vue
- src/core/misc/Stats.ts
- src/core/misc/index.ts
> fix: Uncaught SyntaxError: ambiguous indirect export: stats

- docs/.vitepress/config.ts
- docs/guide/directives/v-light-helper.md
- playground/src/pages/directives/vLightHelper.vue
- playground/src/pages/directives/vLog.vue
- playground/src/pages/index.vue
- playground/src/router/index.ts
- playground/src/router/routes/directives.ts
- playground/src/router/routes/index.ts
- src/core/directives/index.ts
- src/core/directives/vLightHelper.ts
This will not close the issue 178
> feat(cientos): 178 v-light-helper

- src/core/abstractions/Levioso.vue
Closes #208
https://github.com/Tresjs/cientos/assets/20469369/01627092-cb86-4b94-99fe-6462adf418e0
https://github.com/Tresjs/cientos/assets/20469369/38646d60-1d20-4f53-b332-fe10ca391c2e
I took the initiative to do a few refactors, each in separate commits:
* Removing an unexposed, unchanging `ref`: `offset`
* Extracting and naming constants, and "hiding" them in a closure
* Removing some nullish checks on `props.range`
Please especially have a look at the last one:
`props.range` is assigned a default value. It seems to me that it can't be `null` or `undefined`. It's typed as `[number, number]`, so the type checker should signal an error, e.g., if `:range="[1]"`.
The other `props` fields don't have null checks.
So I removed the null checks on `props.range`, but maybe I'm missing something. …
> fix(Levioso): changing speed causes jerkiness

- src/core/controls/OrbitControls.vue
Closes #249
In Cientos' `<OrbitControls />`, the camera and update functions aren't exposed.
Expose a ref to the component using Vue's `defineExpose`. This is the approach taken by other Cientos' components, e.g., Levioso:
https://github.com/Tresjs/cientos/blob/106914ecbad38c65abb534f1f083e235ca370dc0/src/core/abstractions/Levioso.vue#L23
With this PR, the camera is accessible via `[refName].value.value.object`. Update() is available via `[refName].value.value.update`.
> fix(OrbitControls): expose ref

- .gitignore
* .DS_Store files outside of the root directory aren't being ignored
* /docs/components.d.ts is autogenerated and gets created/updated whenever a docs component is created/updated – leading to merge conflicts
Change .gitignore
* Modify `.DS_Store` => `**/.DS_Store` [(to also ignore in all subdirectories)](https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder)
* Add `docs/components.d.ts` to .gitignore
> chore: ignore .DS_Store everywhere, components.d.ts

- .gitignore
All of ./docs/ was included in .gitignore by mistake (by me). 
Removing.
> revert(docs): remove docs/ from .gitignore

- .gitignore
- docs/.vitepress/config.ts
- docs/.vitepress/theme/components/SuperformulaDemo.vue
- docs/.vitepress/theme/components/SuperformulaLechesDemo.vue
- docs/guide/shapes/superformula.md
- playground/src/pages/shapes/SuperformulaDemo.vue
- playground/src/router/routes/shapes.ts
- src/core/shapes/Superformula.vue
- src/core/shapes/index.ts
Closes #270
* Run `pnpm run docs:dev` and see `/guide/shapes/superformula.html`.
* Run `pnpm run playground` and see `/shapes/superformula`.
NOTE: Uses the unmerged `.gitignore` from [this PR.](https://github.com/Tresjs/cientos/pull/272)
> feat(Superformula): add superformula

- package.json
- pnpm-lock.yaml
- src/core/misc/StatsGl.ts
Stats-gl now supports postprocessing and multiple render per loop. The API changed a bit so I reflected the changes here.
> feat: Stats-gl v2

- docs/guide/abstractions/text-3d.md
> fix: wrap `Text3D` inside `Suspense` in the docs

- playground/src/pages/misc/HTMLDemo.vue
- src/core/misc/html/HTML.vue
> fix: remove wrapper element on unmounted

- docs/guide/index.md
The link to "core" in the docs ...
```
Cientos (Spanish word for "hundreds", pronounced `/θjentos/` ) is a 
collection of useful ready-to-go helpers and components that are not 
part of the [core](...) package.
```
... was pointing to the Cientos guide and not to Tres. Tres is the "core".
Update the link to point to `https://tresjs.org/`.
(Also cleaned up a couple of typos.)
> chore(docs): fix link to Tres, typos

- docs/.vitepress/config.ts
- docs/.vitepress/theme/components/BakeShadowsDemo.vue
- docs/guide/misc/bake-shadows.md
- playground/src/pages/misc/BakeShadows.vue
- playground/src/router/routes/misc.ts
- src/core/misc/BakeShadows.ts
- src/core/misc/Stats.ts
- src/core/misc/StatsGl.ts
- src/core/misc/index.ts
closes #321  
How can I remove these warnings
> feat: add BakeShadows component

- src/core/loaders/useGLTF/index.ts
Added conditional return type to infer the actual return type when passing strings or arrays as currently it always return GTLFResult and that is not always correct.
With proposed changes
The type is correctly set and allows me to do this
> fix: Correct return type for useGLTF composable

- src/core/loaders/useGLTF/index.ts
Changes to src/core/loaders/useGLTF/index.ts are causing the CI/CD linter to fail. The changes were merged to `main`, so fresh PRs based on up-to-date `main` also throw errors.
`pnpm run lint --fix` on `main`
> chore(useGLTF): fix linter errors

- docs/guide/staging/backdrop.md
Fixed a typo for the `receive-shadow` prop of `<Backdrop>` in the Usage section. https://cientos.tresjs.org/guide/staging/backdrop.html#usage
> chore(docs): Fix typo `recieve-shadow` to `receive-shadow`

- docs/.vitepress/theme/components/KeyboardControlsDemo.vue
- docs/guide/controls/keyboard-controls.md
- playground/src/pages/controls/KeyboardControls.vue
- playground/src/pages/controls/PointerLockControls.vue
- playground/src/router/routes/controls.ts
- src/core/controls/KeyboardControls.vue
Please check the playground, and play with it, lt me know what you think.
closes #227
> feat(app)!: 227 Change the keyboardcontrols implementation

- src/core/controls/TransformControls.vue
closes #366
Since TransformControls needs a camera in the constructor and I haven't found a way to change the camera once it is instantiated the solution I found is to add a :key to force it to be recreated.
This probably has to be considered for all components where the camera (or other dependencies) is used in the constructor and there is no proper way of setting it after it was created?
> fix: transformControls throws error when switching active camera

- docs/guide/abstractions/fbo.md
- docs/guide/abstractions/use-fbo.md
- docs/guide/materials/custom-shader-material.md
A few demos had line numbers written like this:
```
{2,4,5,6,7,8,9,10,11,20}
```
Write them like this ...
```
{2,4-11,20}
```
... for easier readability/maintenance.
The demo for materials/custom-shader-material had changed, but the line number highlights weren't updated.
Update the line number highlights.
> docs: clean up demo line number highlights

- .github/workflows/actions/pnpm/action.yml
- .husky/install.mjs
- .husky/pre-push
- package.json
- pnpm-lock.yaml
Adds a Git pre-push hook that lints the project. 
* If there are linter errors/warnings:
- the push is stopped
- the errors/warnings are printed
- an explanatory message is printed – see [.husky/pre-push](https://github.com/Tresjs/cientos/compare/chore/git-pre-push-lint?expand=1#diff-43bbc75a027a43baaddc57670d8ab49b4aa2981053c3cabba17567723d3a9fb6) in the commit
* If there are no linter errors/warnings, the push continues.
Discussed on TresJS: https://github.com/Tresjs/tres/issues/590
You can run the hook without actually pushing if you ...
```
git push --dry-run <... extra args>
```
You can skip the hook during a push if you ...
```
git push --no-verify <... extra args>
```
(NOTE: This is mentioned in the console if linting fails.)
@JaimeTorrealba @alvarosabu – What do you think?
> chore: add pre-push linter hook

- docs/guide/staging/environment.md
- playground/src/pages/staging/EnvironmentDemo.vue
- src/core/staging/index.ts
- src/core/staging/useEnvironment/component.vue
- src/core/staging/useEnvironment/const.ts
- src/core/staging/useEnvironment/envSence.ts
- src/core/staging/useEnvironment/index.ts
- src/core/staging/useEnvironment/lightformer/index.vue
Modified at: https://github.com/Tresjs/cientos/pull/374
Preview: https://hawk86104.github.io/#/plugins/skyBox/newEnvironment 
&& https://hawk86104.github.io/#/plugins/industry4/showLambo
**modifying the Environment, enabling us to replicate R3F use cases using Vue3**
```vue
<Suspense>
<Environment :blur="1" background :far="10000">
<Lightformer :intensity="0.75" :rotation-x="Math.PI / 2" :position="[0, 5, -9]" :scale="[10, 10, 1]" />
<Lightformer :intensity="4" :rotation-y="Math.PI / 2" :position="[-5, 1, -1]" :scale="[20, 0.1, 1]" />
<Lightformer :rotation-y="Math.PI / 2" :position="[-5, -1, -1]" :scale="[20, 0.5, 1]" />
<Lightformer :rotation-y="-Math.PI / 2" :position="[10, 1, 0]" :scale="[20, 11, 1]" />
<Levioso :speed="5" :floatFactor="2" :rotationFactor="2">
<Lightformer form="ring" …
```
> feat(app): Add Environment, allowing it to mount sub-components and Lightformer via FBO

- docs/guide/controls/camera-controls.md
- src/core/controls/CameraControls.vue
- src/core/controls/index.ts
- src/utils/types.ts
- Fixes https://github.com/Tresjs/cientos/issues/384
- Adds support for `mouseButtons` and `touches` prop.
- Adds default `mouseButtons` and `touches` prop values based on https://yomotsu.github.io/camera-controls/examples/config.html
- Adds support for partial overrides of `mouseButtons` and `touches`.
- Updates documentation of `CameraControls`
---
Feel free to point out at any mistakes and discrepancies from conventions. I have a strong React background, and some aspects of Vue are kinda new to me 😜
> fix: camera controls ignored props

- playground/src/pages/staging/EnvironmentDemo.vue
- src/core/staging/useEnvironment/component.vue
- src/core/staging/useEnvironment/index.ts
Just fixing some eslint issues
> refactor(tools): Fix some eslint issues

- docs/.vitepress/theme/components/PositionalAudioDemo.vue
- docs/guide/abstractions/positional-audio.md
- playground/src/pages/abstractions/PositionalAudio.vue
- src/core/abstractions/PositionalAudio.vue
Cientos' `main` is failing the CI linter step.
The `<PositionalAudio />` component got committed to `main`. It has linter errors according to the recently updated eslint rules.
Since the linter errors have been merged into `main`, branches based on `main` also can't pass the local linter and fail the CI linter.
Fixed the linter errors in `<PositionalAudio />`.
@damienmontastier , first: no worries. I imagine this is just a case of PR making it into `main` around the time the linter rules were updated.
Second: I've verified that the component works to the best of my knowledge, but please have a look. The linter was unable to automatically fix a number of reported errors, so I had to make a number of changes by hand. 
Third: feel free to ignore here and open a fresh PR with your fixes.
I …
> chore: fix linter errors

- src/core/staging/useEnvironment/lightformer/index.vue
`defineProps` is `import`ed into `src/core/staging/useEnvironment/lightformer/index.vue`. [It's a macro](https://vuejs.org/guide/components/props.html#props-declaration), so it doesn't need to be imported.
The import is causing this warning while running the playground:
Remove the `defineProps` import.
At the moment, the CI step is failing all PRs because `main` contains linter errors. The file touched by this PR passes the linter.
> chore(lightformer): remove defineProps import

- src/core/staging/Fit.vue
- src/core/staging/Sparkles/component.vue
The new linter rules remove markdown formatting in some circumstances. #398
For the affected text, change:
```
/**
* * list item 1
* * list item 2
**/
```
to: 
```
/**
* - list item 1
* - list item 2
**/
```
> chore: guard against overzealous md/jsdoc linting

- docs/guide/abstractions/mouse-parallax.md
- playground/src/pages/abstractions/MouseParallaxDemo.vue
- src/core/abstractions/MouseParallax.vue
This is an add to the props of the `MouseParallax`component.
If the prop `local` is set to true, the mouse coordinates and the `width` and `height` are calculated locally from the canvas, not from the window.
> feat(cientos): local mouseparallax 

- docs/.vitepress/theme/components/AnimatedSpriteNamedAnimationDemo.vue
- docs/guide/abstractions/animated-sprite.md
- src/core/abstractions/AnimatedSprite/AtlasAnimationDefinitionParser.ts
- src/core/abstractions/AnimatedSprite/component.vue
* Fix infinite loop (discussed on Discord)
* Remove explicit fallthrough attribute attachment  – was blocking "@click"
* Move "@click" from `<TresCanvas />` – not working
* Convert props table to HTML
> fix: AnimatedSprite

- src/core/materials/meshReflectionMaterial/index.vue
`<MeshReflectionMaterial />` throws whenever it's included in a scene. 
The local `onBeforeRender` function in the file is called by the material, but the call doesn't send the arguments in the expected order.
It's not necessary for `onBeforeRender` to be called by the material, since it's called during `useLoop().onBeforeRender()`.
Removed the call by the material.
> fix(MeshReflectionMaterial): remove unneeded material.onBeforeRender

- src/core/staging/ContactShadows.vue
The CI linter throws on code generated by the local linter. The code in question is an oddly formatted statement.
Rewrite the oddly formatted statement more simply.
> chore(lint): reformat to avoid linter error

- docs/.vitepress/config.ts
- docs/component-list/components.ts
- docs/guide/materials/mesh-discard-material.md
- playground/vue/src/pages/materials/MeshDiscardMaterialDemo.vue
- playground/vue/src/router/routes/materials.ts
- src/core/materials/index.ts
- src/core/materials/meshDiscardMaterial/index.vue
- src/core/materials/meshDiscardMaterial/material.ts
- src/core/staging/ContactShadows.vue
Port of Drei's `MeshDiscardMaterial`.
Adds:
* component
* playground
* docs
> feat(MeshDiscardMaterial): add component, playground, docs

- docs/.vitepress/theme/components/PositionalAudioDemo.vue
- docs/guide/abstractions/positional-audio.md
- src/core/abstractions/PositionalAudio.vue
[Local Playground](http://localhost:5173/abstractions/positional-audio) — `pnpm run playground`
[Local Documentation](http://localhost:5173/guide/abstractions/positional-audio.html) — `pnpm run docs:dev`
___
The component `<PositionalAudio/>` demo was currently broken on [cientos](https://cientos.tresjs.org/guide/abstractions/positional-audio.html). At the time I developed this component, we hadn't yet migrated to `.instance`. So I reviewed the documentation, demo of the documentation.
> fix(positional-audio): instance properties and fix demo

- docs/guide/controls/keyboard-controls.md
- src/core/controls/KeyboardControls.vue
#573
Use key codes, e.g. `KeyW` rather than `w`. Closes #573 
There are a few wording and formatting issues in the `<KeyboardControls />` docs page.
Update docs.
> fix(KeyboardControls): support non-qwerty keyboards (#573)

- playground/vue/src/pages/staging/environment/EnvironmentDemo.vue
- playground/vue/src/pages/staging/environment/Lightformers.vue
- playground/vue/src/router/routes/staging.ts
- src/core/staging/useEnvironment/EnvironmentScene.ts
- src/core/staging/useEnvironment/component.vue
- src/core/staging/useEnvironment/envSence.ts
- src/core/staging/useEnvironment/lightformer/index.vue
Closes #581 
@hawk86104 you were close with the slots watcher, it was one of the reasons, I just improved a couple of things. It should work now
https://github.com/user-attachments/assets/ab987223-9ec8-4de4-9394-812d8a4b4abc
> fix: 581 environment lightformers are not working

- src/core/misc/html/HTML.vue
Fixes #601.
Has benchmark been conducted on the need for the `will-change` property as [suggested by MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)? On my part I have seen no change of performance, but my html content is limited.
> fix: remove will-change that makes Html components blurry

- package.json
- playground/vue/package.json
- pnpm-lock.yaml
- Upgraded @tresjs/core from 4.3.1 to 4.3.5 for improved functionality and bug fixes.
- Updated @types/three from 0.172.0 to 0.176.0 to ensure compatibility with the latest Three.js features.
- Adjusted package.json and pnpm-lock.yaml accordingly to reflect these changes.
> fix(deps): update @tresjs/core and @types/three to latest versions

- package.json
- playground/vue/src/pages/abstractions/GlobalAudioDemo.vue
- playground/vue/src/pages/controls/ScrollControlsDemo.vue
- pnpm-lock.yaml
- src/core/abstractions/GlobalAudio.ts
- src/core/abstractions/MouseParallax.vue
- src/core/abstractions/PositionalAudio.vue
- src/core/abstractions/useFBO/index.ts
- src/core/controls/CameraControls.vue
- src/core/controls/KeyboardControls.vue
- src/core/controls/MapControls.vue
- src/core/controls/OrbitControls.vue
- src/core/controls/PointerLockControls.vue
- src/core/controls/ScrollControls.vue
- src/core/controls/TransformControls.vue
- src/core/misc/html/HTML.vue
- src/core/staging/AccumulativeShadows/component.vue
- src/core/staging/Bounds/component.vue
- src/core/staging/Smoke.vue
- src/core/staging/SoftShadows.vue
- Removed the unused `Camera` type import from `index.ts` in the `useFBO` module to clean up the code and improve maintainability.
> feat: 615-adapt-camera-dependant-abstractions-to-core-v5-camera-changes

- src/core/abstractions/Billboard.vue
- src/core/abstractions/Image/component.vue
- src/core/abstractions/ScreenSpace.vue
- src/core/abstractions/Text3D.vue
- src/core/abstractions/useSurfaceSampler/index.ts
- src/core/controls/Helper/component.vue
- src/core/controls/Helper/useHelper.ts
- src/core/materials/meshGlassMaterial/material.ts
- src/core/staging/ContactShadows.vue
- src/core/staging/Sky.vue
- src/core/staging/Sparkles/component.vue
- Updated `Sky.vue` to directly expose the `skyImpl` instance instead of using a shallow reference, improving clarity and performance.
- Removed the unused `sparkleRef` in `Sparkles/component.vue`, simplifying the component structure while maintaining functionality.
- These changes enhance code maintainability and align with best practices for instance management in Vue components.
> refactor: streamline instance exposure and remove unused refs

- docs/guide/loaders/use-fbx.md
- docs/guide/loaders/use-gltf.md
- src/core/loaders/useFBX/index.ts
- src/core/loaders/useGLTF/component.vue
- src/core/loaders/useGLTF/index.ts
- Adds a `traverse` option to the `useFBX` and `useGLTF` composables to enable workflows like:
```ts
const { state } = useGLTF("/foo.gltf", {
traverse(child) { /* ... */ }
})
// Instead of
const { state } = useGLTF("/foo.gltf")
watch(state, (state) => {
state.scene.traverse((child) => { /* ... */ })
})
```
- Updates documentation to reflect the new `traverse` option.
- Aligns `GLTFModel` props behavior with `FBXModel`'s, shadow should be reactive now.
Let me know if anything! Also, I'm not suggesting this strongly and am completely open to suggestions! This just sparked up from a Discord convo with @alvarosabu.
> feat: add `traverse` option to model loaders

- src/core/staging/Precipitation.vue
Small change to fix "When speed parameter change, the position of the particles change"
(Before | After)
> fix: precipitation speed
