src/core/controls/OrbitControls.vue
=> fix: added missing prop target and removed withDefaults

.eslintrc.cjs, playground/.eslintrc-auto-import.json, playground/auto-imports.d.ts, playground/components.d.ts, playground/src/components/PrecipitationDemo.vue, playground/src/pages/index.vue, src/core/abstractions/Precipitation.vue, src/core/abstractions/Stars.vue, src/core/abstractions/useParallax/index.ts
- add console error rule in linter
- rmv log in MouseParallax
- fix precipitation error when area not provided
=> fix: precipitation issue, rmv log mouseparallax, add rule lint

docs/.vitepress/config.ts, docs/guide/loaders/use-progress.md, playground/.eslintrc-auto-import.json, playground/auto-imports.d.ts, playground/components.d.ts, playground/src/components/EnvironmentDemo.vue, playground/src/pages/index.vue, src/core/abstractions/index.ts, src/core/abstractions/useProgress.ts, src/core/loaders/useProgress.ts
=> feat: useProgress composable

docs/guide/controls/transform-controls.md
=> docs(transform-controls): fix typo and spacing

src/core/controls/KeyboardControls.vue
=> fix: initial camera position in keyboard controls

playground/src/components/ScrollDemo.vue, src/core/controls/ScrollControls.vue
close #129 
this should fix the issue, but there's a way to try on nuxt from here?
=> fix: nuxt problem with scrollControls

docs/guide/loaders/use-fbx.md, docs/guide/loaders/use-gltf.md
Update the docs in useGLTF and useFbx to use primitive
=> docs: use primitive in the example, docs

docs/.vitepress/config.ts, docs/guide/controls/camera-controls.md, package.json, playground/src/pages/CameraControlsDemo.vue, playground/src/router.ts, pnpm-lock.yaml, src/core/controls/CameraControls.vue, src/core/controls/index.ts
=> feat: add preliminary camera-controls abstraction

docs/guide/misc/use-tweakpane.md, package.json, stats.html, vite.config.ts
Closes #168 
|  | Size | Gzip |
|--------|--------|--------|
| Prev | 654.80 kB | 137.27 kB |
| Now | 337.46 kB | 80.99 kB |
=> feat: remove tweakpane deps from final bundle

docs/.vitepress/config.ts, docs/guide/materials/glass-material.md, playground/src/components/GlassMaterialDemo.vue, playground/src/pages/index.vue, src/core/materials/index.ts, src/core/materials/meshGlassMaterial/index.vue, src/core/materials/meshGlassMaterial/material.ts
closes #159 
Please try it, and let me know what you think @alvarosabu
=> feat: add glass material

package.json, playground/package.json, playground/src/pages/ScrollControlsDemo.vue, pnpm-lock.yaml, src/core/controls/ScrollControls.vue
=> fix: removed `toFixed` for progress value

playground/src/pages/staging/EnvironmentDemo.vue, src/core/staging/useEnvironment/const.ts, src/core/staging/useEnvironment/index.ts
=> fix: check background prop if its empty string

playground/src/pages/misc/Card.vue, playground/src/pages/misc/HTMLDemo.vue, src/core/misc/html/HTML.vue
=> fix: avoid html container to be appended again

src/core/misc/StatsGl.ts
=> fix(app): 336 Fix stats-gl problem

src/core/loaders/useGLTF/index.ts
thx @Sea-DH1 :[Sea-DH1](https://github.com/Sea-DH1) 
QAFrom: https://github.com/Tresjs/cientos/pull/127
=> feat(cientos): auto useDracoLoaderDispose in useGLTF

playground/src/pages/abstractions/LensflareDemo.vue
=> fix(Lensflare demo): add camera #435

docs/.vitepress/config.ts, docs/.vitepress/theme/components/BillboardDemo.vue, docs/component-list/components.ts, docs/guide/abstractions/billboard.md, playground/vue/src/pages/abstractions/BillboardDemo.vue, playground/vue/src/router/routes/abstractions.ts, src/core/abstractions/Billboard.vue, src/core/abstractions/index.ts, src/core/staging/ContactShadows.vue
Port of Drei's `<Billboard />` component.
Adds:
* component
* playground
* docs
=> feat(Billboard): add component, playground, docs

docs/.vitepress/config.ts, docs/.vitepress/theme/components/ScreenQuadDemo.vue, docs/component-list/components.ts, docs/guide/shapes/screen-quad.md, playground/vue/src/pages/shapes/ScreenQuadDemo.vue, playground/vue/src/router/routes/shapes.ts, src/core/shapes/ScreenQuad.vue, src/core/shapes/index.ts, src/core/staging/ContactShadows.vue, src/utils/shaderMaterial.ts
Port of Drei's `<ScreenQuad />`.
Adds:
* component
* playground
* docs
=> feat(ScreenQuad): add component, playground, docs

docs/.vitepress/config.ts, docs/.vitepress/theme/components/CubicBezierLineDemo.vue, docs/component-list/components.ts, docs/guide/shapes/cubic-bezier-line.md, playground/vue/src/pages/shapes/CubicBezierLineDemo.vue, playground/vue/src/router/routes/shapes.ts, src/core/shapes/CubicBezierLine.vue, src/core/shapes/index.ts
Ports Drei's `<CubicBezierLine />` to Cientos. Adds:
* component
* demo
* docs
=> feat(CubicBezierLine): add component, demo, docs

docs/guide/staging/align.md, src/core/staging/Align.vue
* replaces `on-align="callback"` prop with `@update` and `@change` emits
* renames emit argument type
=> refactor(Align): change callback to emit, improve naming

docs/.vitepress/config.ts, docs/.vitepress/theme/components/LODDemo.vue, docs/component-list/components.ts, docs/guide/misc/lod.md, playground/vue/src/pages/misc/LODDemo.vue, playground/vue/src/router/routes/misc.ts, src/core/misc/LOD.vue, src/core/misc/index.ts, src/core/staging/ContactShadows.vue
Adds:
* component wrapper for [THREE.LOD](https://threejs.org/docs/?q=LOD#api/en/objects/LOD)
* playground
* docs
Closes #393
=> feat(LOD): add component, playground, docs

src/core/misc/html/HTML.vue, src/core/misc/html/utils.ts
=> fix: update html on camera dolly zoom

src/core/controls/TransformControls.vue
Quick PR I did on the fly. I didn't even clone the repo. Let me know if we need anything else along this PR.
fixes #614
=> fix(transform-controls): use correct emit on mouse up

src/core/staging/Precipitation.vue
Small PR to correct the missing import watch for precipitation component
=> fix: missing importing watch for precipitation component
